### ISSUE TITLE
Html syntax not rendering

### ISSUE THREAD

**Issue by albrtogarcia** [olssonm/ampersand#6]
Hi, first of all, thank you for your work :)

I have a doubt: markdown by default supports [html syntax](https://daringfireball.net/projects/markdown/syntax#html) but when I put some html code in a `.md` blog post file, it doesn't render.

Am I missing something or it's the package expected behavior?

Thanks so much, best regards.

**Comment by olssonm** [comment]
@albrtogarcia Thanks for your feedback! I'll look into it ASAP – but yes, of course HTML should get rendered.

**Comment by olssonm** [comment]
@albrtogarcia Okay, ran some tests and I don't seem to be able to replicate the issue, for instance:

```html
<a href="#">Test</a>
```

and even

```html
<div>
    <div>
        Test
    </div>
</div>
```

Renders as it should. Do you have some example markdown that  I can look into?

**Comment by albrtogarcia** [comment]
Thank you so much @olssonm.

When I put this:

```
# Title

<div class="alert"><a href="https://www.docker.com/">Docker</a></div>

Lorem ipsum dolor sit amet, consectetetur adipispling elit sed do eiusm.
```

Only renders this:

```html
<h1>Title</h1>
<p>Lorem ipsum dolor sit am et, consectet etur adipis cing el s sed do eiusm</p>
```

Now that I know that it should work I will run a test in a fresh Laravel install to discard conflicts with other packages.

I'll let you know the results.

Thank you again, best regards 😄

**Comment by olssonm** [comment]
@albrtogarcia How odd! The exact same snippet renders for me as it should:

<img width="700" alt="Screenshot 2022-06-09 at 12 17 16" src="https://user-images.githubusercontent.com/907114/172824697-b210f046-ec96-4208-9423-81823d206cba.png">

Do you know if you use and/or register `league/commonmark` anywhere else in your application? I can also take your version off `league/commonmark` in your composer.lock-file (technically my package `olssonm/ampersand` supports both 1.0 and 2.0, but that perhaps something changed during that version-bump – that's why I'm asking).

**Comment by albrtogarcia** [comment]
Good news, in a fresh install works as expected.

Then we´ve looked for inconsistencies with other markdown related packages previously installed and we found that uninstalling `graham-campbell/markdown` package make yours work again. This package remained from a previous blog try.

In composer.lock we have `league/commonmark@2.3.3`.

Many thanks again, I owe you a couple of beers 🍻 (or whatever you like).

Have a nice day 👋

**Comment by olssonm** [comment]
Gotcha. For future reference; looks like there was a clash with `graham-campbell/markdown`. In that package's settings the default is:

```
'html_input' = 'strip'
```

Which somehow "bleeds over" to `olssonm/ampersand`.

Will look into isolating this in the future.
